# Generated by Django 5.2.7 on 2025-10-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='cat',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cat',
            name='speciality',
            field=models.CharField(default='CatSpecial', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidatelist',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatecat', to='adoption.cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cat',
            name='biography',
            field=models.TextField(default='CatBio', max_length=400),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(default='CatBreed', max_length=100),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(default='CatName', max_length=100),
        ),
    ]
