# Generated by Django 5.2.7 on 2025-11-01 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_candidatelist_user_alter_cat_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatelist',
            name='cat',
        ),
        migrations.AddField(
            model_name='candidatelist',
            name='cats',
            field=models.ManyToManyField(blank=True, related_name='candidate_lists', to='adoption.cat'),
        ),
        migrations.AlterField(
            model_name='candidatelist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
