# Generated by Django 5.2.7 on 2025-11-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_remove_candidatelist_cat_candidatelist_cats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatelist',
            old_name='cats',
            new_name='cat',
        ),
    ]
