# Generated by Django 5.2.7 on 2025-11-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='biography',
            field=models.TextField(default='CatBio', max_length=1000),
        ),
    ]
